services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data

  websocket_bot:
    build:
      context: .
      dockerfile: bots/websocket_bot/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BOT_AUTH_TOKEN: ${WEBSOCKET_BOT_AUTH_TOKEN}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./bots/websocket_bot:/app
      - ./bots/utils:/app/utils
      - ./bots/config:/app/config

  db_bot:
    build:
      context: .
      dockerfile: bots/db/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BOT_AUTH_TOKEN: ${DB_BOT_AUTH_TOKEN}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_TRADING_SCHEMA: ${DB_TRADING_SCHEMA}
    volumes:
      - ./bots/db:/app
      - ./bots/utils:/app/utils
      - ./bots/config:/app/config

  preprocessor_bot:
    build:
      context: .
      dockerfile: bots/preprocessor/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BOT_AUTH_TOKEN: ${PREPROCESSOR_BOT_AUTH_TOKEN}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./bots/preprocessor:/app
      - ./bots/utils:/app/utils
      - ./bots/config:/app/config

  macro_metrics:
    build:
      context: .
      dockerfile: bots/macro_metrics/Dockerfile
    depends_on:
      - redis
    environment:
      BOT_AUTH_TOKEN: ${MACRO_SERVICES_BOT_AUTH_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./bots/macro_metrics:/app
      - ./bots/utils:/app/utils
      - ./bots/config:/app/config

  trigger_bot:
    build:
      context: .
      dockerfile: bots/trigger/Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      BOT_AUTH_TOKEN: ${TRIGGER_BOT_AUTH_TOKEN}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_TRADING_SCHEMA: ${DB_TRADING_SCHEMA}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
    volumes:
      - ./bots/trigger:/app
      - ./bots/utils:/app/utils
      - ./bots/config:/app/config

volumes:
  postgres-data:
  redis-data: